### ISSUE TITLE
Can I use this library with floats ?

### ISSUE THREAD

**Issue by greenersharp** [ayman-albaz/distances#1]
Hi,

I noticed all the examples for your library work with seqs of integers.    

I wanted to calculate distances between word vectors,  which are seqs of floats.  

What's the reason the library doesn't work with floats?  I would think it would be a very common use case with machine learning, most data is in floats.

Thanks

**Comment by ayman-albaz** [comment]
> Hi,
> 
> I noticed all the examples for your library work with seqs of integers.
> 
> I wanted to calculate distances between word vectors, which are seqs of floats.
> 
> What's the reason the library doesn't work with floats? I would think it would be a very common use case with machine learning, most data is in floats.
> 
> Thanks

Yes you can, please see the tests module as an example of how you can use floats. The required type is SomeNumber which can be either int or float.

Also I haven't updated this library in a couple of years to feel free to make a PR with any fixes or additional features you may want.

**Comment by greenersharp** [comment]
I'm not sure why I'm getting an error.

I am passing two vectors, which are both seqs[float32] of the same length,  into cosine_distance and I am getting the following error:

`echo cosine_distance(vec1, vec2)`

![Screenshot from 2024-01-30 22-40-37](https://github.com/ayman-albaz/distances/assets/104863406/e4568c69-0e0e-4cac-817d-bea21b2587e7)

I'm not quite sure what I'm doing wrong.

**Comment by ayman-albaz** [comment]
> I'm not sure why I'm getting an error.
> 
> I am passing two vectors, which are both seqs[float32] of the same length, into cosine_distance and I am getting the following error:
> 
> `echo cosine_distance(vec1, vec2)`
> 
> ![Screenshot from 2024-01-30 22-40-37](https://private-user-images.githubusercontent.com/104863406/301032403-e4568c69-0e0e-4cac-817d-bea21b2587e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2Nzk0MTUsIm5iZiI6MTcwNjY3OTExNSwicGF0aCI6Ii8xMDQ4NjM0MDYvMzAxMDMyNDAzLWU0NTY4YzY5LTBlMGUtNGNhYy04MTdkLWJlYTIxYjI1ODdlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwNTMxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWYwYTFiZGM4NzQ1NmQwMzc3ODE2NWRiNzA1MmVlZGY3OTE2M2RiZThhNjRkOTY0Yzk0ZDk3ZGI2NzhlYTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z9KB95aY74grFItczx6ar9_Y_Rt5JWrdtXZqhHVllZ4)
> 
> I'm not quite sure what I'm doing wrong.

You are using the incorrect submodule. Please make sure you are importing correctly with `import distances/seq`. Please see the tests in this library to see an example.

**Comment by greenersharp** [comment]
Thank you, works great !
